import{dom}from 'https://gitcdn.link/cdn/anliting/simple.js/55124630741399dd0fcbee2f0396642a428cdd24/src/simple.static.js'
import style from './Keyboard/style.js'
import createKeyNodes from './Keyboard/createKeyNodes.js'
import lowerKey from './Keyboard/lowerKey.js'
function Keyboard(){
    this._keyNodes=createKeyNodes()
    this.node=dom.div({className:'keyboard'},
        dom.div({className:'table'},
            dom.div(
                dom.div(
                    dom.div({className:'escape'},
                        n=>{dom(n.style,{display:'inline-block'})},
                        this._keyNodes['Escape'][0],
                    ),
                    dom.div({className:'function'},
                        n=>{dom(n.style,{display:'inline-block'})},
                        this._keyNodes['F1'][0],
                        this._keyNodes['F2'][0],
                        this._keyNodes['F3'][0],
                        this._keyNodes['F4'][0],
                        this._keyNodes['F5'][0],
                        this._keyNodes['F6'][0],
                        this._keyNodes['F7'][0],
                        this._keyNodes['F8'][0],
                        this._keyNodes['F9'][0],
                        this._keyNodes['F10'][0],
                        this._keyNodes['F11'][0],
                        this._keyNodes['F12'][0],
                    ),
                ),
                dom.div(
                    dom.div({className:'legacy'},
                        this._keyNodes['Print'][0],
                        this._keyNodes['ScrollLock'][0],
                        this._keyNodes['Pause'][0],
                    ),
                ),
                dom.div(
                ),
            ),
            dom.div(
                dom.div(
                    dom.div({className:'row'},
                        this._keyNodes['`'][0],
                        this._keyNodes[1][0],
                        this._keyNodes[2][0],
                        this._keyNodes[3][0],
                        this._keyNodes[4][0],
                        this._keyNodes[5][0],
                        this._keyNodes[6][0],
                        this._keyNodes[7][0],
                        this._keyNodes[8][0],
                        this._keyNodes[9][0],
                        this._keyNodes[0][0],
                        this._keyNodes['-'][0],
                        this._keyNodes['='][0],
                        this._keyNodes.Backspace[0],
                    ),
                    dom.div({className:'row'},
                        this._keyNodes.Tab[0],
                        this._keyNodes.q[0],
                        this._keyNodes.w[0],
                        this._keyNodes.e[0],
                        this._keyNodes.r[0],
                        this._keyNodes.t[0],
                        this._keyNodes.y[0],
                        this._keyNodes.u[0],
                        this._keyNodes.i[0],
                        this._keyNodes.o[0],
                        this._keyNodes.p[0],
                        this._keyNodes['['][0],
                        this._keyNodes[']'][0],
                        this._keyNodes['\\'][0],
                    ),
                    dom.div({className:'row'},
                        this._keyNodes.CapsLock[0],
                        this._keyNodes.a[0],
                        this._keyNodes.s[0],
                        this._keyNodes.d[0],
                        this._keyNodes.f[0],
                        this._keyNodes.g[0],
                        this._keyNodes.h[0],
                        this._keyNodes.j[0],
                        this._keyNodes.k[0],
                        this._keyNodes.l[0],
                        this._keyNodes[';'][0],
                        this._keyNodes['\''][0],
                        this._keyNodes.Enter[0],
                    ),
                    dom.div({className:'row'},
                        this._keyNodes.Shift[1],
                        this._keyNodes.z[0],
                        this._keyNodes.x[0],
                        this._keyNodes.c[0],
                        this._keyNodes.v[0],
                        this._keyNodes.b[0],
                        this._keyNodes.n[0],
                        this._keyNodes.m[0],
                        this._keyNodes[','][0],
                        this._keyNodes['.'][0],
                        this._keyNodes['/'][0],
                        this._keyNodes.Shift[2],
                    ),
                    dom.div({className:'row'},
                        this._keyNodes.Control[1],
                        this._keyNodes.Meta[1],
                        this._keyNodes.Alt[1],
                        this._keyNodes[' '][0],
                        this._keyNodes.Alt[2],
                        this._keyNodes.Meta[2],
                        this._keyNodes.ContextMenu[0],
                        this._keyNodes.Control[2],
                    ),
                ),
                dom.div(
                    dom.div({className:'navigation'},
                    ),
                ),
                dom.div(
                    dom.div({className:'numeric'},
                    ),
                ),
            ),
        ),
    )
}
Keyboard.prototype._key=function(){
    let now=new Date
    /*if(this._lastKey)
        console.log(now-this._lastKey)*/
    this._lastKey=now
}
Keyboard.prototype.keydown=function(e){
    this._key()
    let key=lowerKey(e.key)
    if(this._keyNodes[key]&&this._keyNodes[key][e.location])
        this._keyNodes[key][e.location].classList.add('keydown')
    else
        console.log(key,e.location)
}
Keyboard.prototype.keyup=function(e){
    this._key()
    let key=lowerKey(e.key)
    if(this._keyNodes[key]&&this._keyNodes[key][e.location])
        this._keyNodes[key][e.location].classList.remove('keydown')
}
Keyboard.style=style
export default Keyboard
